### ISSUE TITLE
Capturing server's IP address

### ISSUE THREAD

**Issue by blalor** [canaryio/canary#36]
I've been looking at the code and the Go docs trying to figure out how to implement this and I'm coming up short.  I don't see a way with `net/http` to get the IP address of the server that sent the response.  `Sampler` [does provide its own `Transport`](https://github.com/canaryio/canary/blob/master/pkg/sampler/sampler.go#L56) which actually creates the connection, but I don't see a clean way to share that information with [`Sampler.Sample`](https://github.com/canaryio/canary/blob/master/pkg/sampler/sampler.go#L70).  

Another approach would be to do the address resolution in `Sampler.Sample`, but the code for doing so is sufficiently complex (ipv4 vs ipv6, etc) that it seems like a liability to reproduce that in Canary.

Thoughts?  I'd like to have this information so I can identify which CDN is failing to serve content, without having to track that in the manifest.

**Comment by blalor** [comment]
@gorsuch ping.  thoughts? :-)

**Comment by gorsuch** [comment]
I've been trying to wrap my head around that myself over the past several months - I want that feature pretty bad.

The best solution I've been able to come up with is the one you enumerated: have `Sampler.Sample` do DNS resolution and use that.  I can take a stab at it if you'd like, and we can try and iron out edge cases.

**Comment by blalor** [comment]
If you’ve already got something in mind, please have at it.  I’d love to test it. :-)

**Comment by blalor** [comment]
Still thinking about this.  `Sampler` is single-threaded, right?  What if we added a `GetLastAddress()` to the `Transport`?

**Comment by gorsuch** [comment]
Oooh.  You wanna take a stab at that?

**Comment by blalor** [comment]
Yes. :-)

**Comment by gorsuch** [comment]
I'm sketching some of this out over here:

https://github.com/canaryio/canary/pull/42

Feedback very much appreciated.

**Comment by gorsuch** [comment]
Fixed via #42.
